#!/bin/bash

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.rs')
if \[ -n "$CHANGED_FILES" \]; then
    rustfmt --edition 2021 $CHANGED_FILES;
    git add $CHANGED_FILES;
fi

exit 0
